version: '3.8'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    container_name: mssql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345678bIba$
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "12345678bIba$$" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    platform: linux/arm64
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=12345678bIba$
      - DB_NAME=flowers_db_2025
      - DB_PORT=1433
    networks:
      - app-network
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
