version: '3.8'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64
    container_name: sql_connect
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=SQLConnect1$
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      # Пытаемся выполнить простой запрос к master базе
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SQLConnect1$", "-Q", "SELECT 1", "-b", "-o", "/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10 # Увеличить количество попыток, т.к. SQL Server может стартовать долго
      start_period: 30s # Дать время на первоначальный запуск перед началом проверок
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    platform: linux/arm64
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=SQLConnect1$
      - DB_NAME=flowers_db_2025
      - DB_PORT=1433
    networks:
      - app-network
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
